Small issues identified in last release PR
quixio/quix-library pull request #367
Opened 2023-03-23 15:54 UTC by SteveRosam

2023-03-23 15:56 UTC, tbedford requested changes

2023-03-23 15:56 UTC, tbedford commented on python/transformations/InMemory-View/library.json
> +    "shortDescription": "A template demonstrating how to build an in memory-view.",
in-memory view

2023-03-24 15:37 UTC, SteveRosam commented
@tbedford can you approve pls

2023-03-24 15:48 UTC, tbedford approved these changes

2023-03-24 15:56 UTC, merged